<?php

return [
    'models' => [
        'Opportunities' => [
            'label' => 'فرصت‌ها',
            'class' => App\Models\Opportunity::class,
            'fields' => [
                // type: string|integer|number|boolean|date|datetime
                'id' => 'integer',
                'name' => 'string',
                'organization_id' => 'integer',
                'contact_id' => 'integer',
                'stage' => 'string',
                'type' => 'string',
                'source' => 'string',
                'assigned_to' => 'integer',
                'success_rate' => 'integer',
                'amount' => 'integer',
                'next_follow_up' => 'date',
                'created_at' => 'datetime',
                'updated_at' => 'datetime',
            ],
            'labels' => [
                'id' => 'شناسه',
                'name' => 'عنوان',
                'organization_id' => 'سازمان',
                'contact_id' => 'مخاطب',
                'stage' => 'مرحله',
                'type' => 'نوع',
                'source' => 'منبع',
                'assigned_to' => 'کاربر مسئول',
                'success_rate' => 'درصد موفقیت',
                'amount' => 'مبلغ',
                'next_follow_up' => 'پیگیری بعدی',
                'created_at' => 'تاریخ ایجاد',
                'updated_at' => 'آخرین تغییر',
            ],
        ],
        'Leads' => [
            'label' => 'سرنخ‌ها',
            'class' => App\Models\Lead::class,
            'fields' => [
                'id' => 'integer',
                'full_name' => 'string',
                'company' => 'string',
                'email' => 'string',
                'mobile' => 'string',
                'phone' => 'string',
                'lead_source' => 'string',
                'lead_status' => 'string',
                'lead_date' => 'date',
                'next_follow_up_date' => 'date',
                'assigned_to' => 'integer',
                'created_at' => 'datetime',
                'updated_at' => 'datetime',
            ],
            'labels' => [
                'id' => 'شناسه',
                'full_name' => 'نام کامل',
                'company' => 'شرکت',
                'email' => 'ایمیل',
                'mobile' => 'موبایل',
                'phone' => 'تلفن',
                'lead_source' => 'منبع سرنخ',
                'lead_status' => 'وضعیت سرنخ',
                'lead_date' => 'تاریخ سرنخ',
                'next_follow_up_date' => 'پیگیری بعدی',
                'assigned_to' => 'کاربر مسئول',
                'created_at' => 'تاریخ ایجاد',
                'updated_at' => 'آخرین تغییر',
            ],
        ],
        'Contacts' => [
            'label' => 'مخاطبین',
            'class' => App\Models\Contact::class,
            'fields' => [
                'id' => 'integer',
                'first_name' => 'string',
                'last_name' => 'string',
                'email' => 'string',
                'phone' => 'string',
                'mobile' => 'string',
                'company' => 'string',
                'organization_id' => 'integer',
                'assigned_to' => 'integer',
                'created_at' => 'datetime',
                'updated_at' => 'datetime',
            ],
            'labels' => [
                'id' => 'شناسه',
                'first_name' => 'نام',
                'last_name' => 'نام خانوادگی',
                'email' => 'ایمیل',
                'phone' => 'تلفن',
                'mobile' => 'موبایل',
                'company' => 'شرکت',
                'organization_id' => 'سازمان',
                'assigned_to' => 'کاربر مسئول',
                'created_at' => 'تاریخ ایجاد',
                'updated_at' => 'آخرین تغییر',
            ],
        ],
        'Organizations' => [
            'label' => 'سازمان‌ها',
            'class' => App\Models\Organization::class,
            'fields' => [
                'id' => 'integer',
                'name' => 'string',
                'email' => 'string',
                'phone' => 'string',
                'industry' => 'string',
                'size' => 'integer',
                'state' => 'string',
                'city' => 'string',
                'assigned_to' => 'integer',
                'created_at' => 'datetime',
                'updated_at' => 'datetime',
            ],
            'labels' => [
                'id' => 'شناسه',
                'name' => 'نام',
                'email' => 'ایمیل',
                'phone' => 'تلفن',
                'industry' => 'صنعت',
                'size' => 'اندازه',
                'state' => 'استان',
                'city' => 'شهر',
                'assigned_to' => 'کاربر مسئول',
                'created_at' => 'تاریخ ایجاد',
                'updated_at' => 'آخرین تغییر',
            ],
        ],
        'Proformas' => [
            'label' => 'پیش‌فاکتورها',
            'class' => App\Models\Proforma::class,
            'fields' => [
                'id' => 'integer',
                'subject' => 'string',
                'proforma_date' => 'date',
                'total_amount' => 'integer',
                'items_subtotal' => 'integer',
                'assigned_to' => 'integer',
                'organization_id' => 'integer',
                'contact_id' => 'integer',
                'opportunity_id' => 'integer',
                'created_at' => 'datetime',
                'updated_at' => 'datetime',
            ],
            'labels' => [
                'id' => 'شناسه',
                'subject' => 'موضوع',
                'proforma_date' => 'تاریخ پیش‌فاکتور',
                'total_amount' => 'مبلغ کل',
                'items_subtotal' => 'جمع اقلام',
                'assigned_to' => 'کاربر مسئول',
                'organization_id' => 'سازمان',
                'contact_id' => 'مخاطب',
                'opportunity_id' => 'فرصت',
                'created_at' => 'تاریخ ایجاد',
                'updated_at' => 'آخرین تغییر',
            ],
        ],
        'Activities' => [
            'label' => 'فعالیت‌ها',
            'class' => App\Models\Activity::class,
            'fields' => [
                'id' => 'integer',
                'subject' => 'string',
                'start_at' => 'datetime',
                'due_at' => 'datetime',
                'assigned_to_id' => 'integer',
                'is_private' => 'boolean',
                'created_by_id' => 'integer',
                'status' => 'string',
                'priority' => 'string',
                'created_at' => 'datetime',
                'updated_at' => 'datetime',
            ],
            'labels' => [
                'id' => 'شناسه',
                'subject' => 'موضوع',
                'start_at' => 'زمان شروع',
                'due_at' => 'موعد',
                'assigned_to_id' => 'مسئول',
                'is_private' => 'خصوصی',
                'created_by_id' => 'ایجادکننده',
                'status' => 'وضعیت',
                'priority' => 'اولویت',
                'created_at' => 'تاریخ ایجاد',
                'updated_at' => 'آخرین تغییر',
            ],
        ],
    ],

    'operators' => [
        'string' => ['eq','neq','like','starts_with','ends_with','in'],
        'integer' => ['eq','neq','gt','gte','lt','lte','in','between'],
        'number' => ['eq','neq','gt','gte','lt','lte','in','between'],
        'boolean' => ['eq'],
        'date' => ['eq','gt','gte','lt','lte','between'],
        'datetime' => ['eq','gt','gte','lt','lte','between'],
    ],

    'aggregates' => ['sum','avg','count','max','min'],

    // Export constraints
    'max_export_rows' => 100000,

    // Currency formatting (for summary display)
    'currency' => [
        'code' => 'IRR',
        'symbol' => '﷼',
        'position' => 'after', // before|after
        'thousands_sep' => ',',
        'decimal_sep' => '.',
        'decimals' => 0,
    ],
];
